### ISSUE TITLE
Model architecture used in GLUE experiment.

### ISSUE THREAD

**Issue by Leonezz** [ylsung/Ladder-Side-Tuning#3]
Hi, I really like your excellent work, it proved the effectiveness of Ladder like architecture.

The side network described in the paper is a lightweight version of the backbone transformer, but in you code base, I found side network implementations of both light weight transformer block version and adapter 
like(bottleneck FFN) version. I wonder which one is used in the NLP GLUE experiment, the lightweight transformer one or adapter like one?

Thanks for your work and reply, this can really help me.

**Comment by ylsung** [comment]
I use the light-weight transformer blocks in the experiments. I also tried the adapter-like architecture in the very beginning of this project, and I remembered it performed a bit worse than the transformer architecture, but I didn't test its performance over all tasks of GLUE.

**Comment by Leonezz** [comment]
Got it! Thanks a lot!
