### ISSUE TITLE
About distill loss

### ISSUE THREAD

**Issue by Leonezz** [ylsung/Ladder-Side-Tuning#4]
Hi, sorry to interrupt again, I noticed that there is distill_loss in your code, may I ask did you use it in you experiments?

**Comment by ylsung** [comment]
The answer is no. I did some experiments to use distillation to initialize the side network instead of the network pruning, but I found they work similarly and network pruning is simpler and faster.

**Comment by Leonezz** [comment]
Thank you very much for the reply!
